export const CONFIG = {
NOMBRE_EMPRESA: "Frankos Chicken",
COLOR_PRIMARIO: "#ea580c",
ICONO_HEADER: "FC",
FAVICON_EMOJI: "🐔",
LOGO_URL: "https://i.ibb.co/W4m7vxxn/logo-frankos-chicken.jpg",
WHATSAPP_NUMERO: "51949973277",
SALUDO_INICIAL: "¡Hola! Bienvenido a Frankos Chicken. ¿En qué puedo ayudarte hoy?",
PLACEHOLDER_INPUT: "Escribe tu consulta...",
SHOW_REMAINING_MESSAGES: true,
WARNING_THRESHOLD: 1,
URL_PROXY: "https://deepseek-chat-proxy.precios-com-pe.workers.dev",
MODELO: "deepseek-chat",
TEMPERATURA: 0.1,
TIMEOUT_MS: 15000,
MAX_TOKENS_RESPONSE: 150,
MAX_HISTORIAL_MESSAGES: 4,
RETRY_LIMIT: 3,
RETRY_DELAY_MS: 1000,
URL_CONFIG_SHEET: "https://docs.google.com/spreadsheets/d/1wZjHdi2taaNd5XiBYYPYKQm_ESG9fo6CP_jY7o7Wfzs/edit?usp=sharing",
CACHE_VERSION: "1.0.0",
MIN_LENGTH_INPUT: 4,
MAX_LENGTH_INPUT: 150,
MAX_DEMO_MESSAGES: 5,
RATE_LIMIT_MAX_REQUESTS: 5,
RATE_LIMIT_WINDOW_SECONDS: 60,
};
